# Generated by Django 5.2 on 2025-11-23 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_expand_site_structure'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Показывать на главной'),
        ),
    ]
