# Generated by Django 5.2 on 2025-11-23 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_project_video_projectimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='benefits',
            field=models.TextField(blank=True, help_text='Почему выбрать эту услугу', verbose_name='Преимущества'),
        ),
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, help_text='Детальное описание услуги для страницы услуг', verbose_name='Подробное описание'),
        ),
        migrations.AddField(
            model_name='service',
            name='process',
            field=models.TextField(blank=True, help_text='Этапы работы над проектом', verbose_name='Процесс работы'),
        ),
        migrations.AddField(
            model_name='service',
            name='technologies',
            field=models.TextField(blank=True, help_text='Используемые технологии и инструменты', verbose_name='Технологии'),
        ),
    ]
