# Generated by Django 5.2.8 on 2025-11-27 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_service_benefits_service_description_service_process_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='overlay_text',
            field=models.CharField(blank=True, help_text='Текст, который будет печататься над активным слайдом (например: "Создайте сайт для...")', max_length=255, verbose_name='Текст поверх слайда'),
        ),
    ]
