# Generated by Django 5.2.8 on 2025-11-27 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_project_overlay_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='brief_text',
            field=models.TextField(blank=True, help_text='Текст технического задания, который показывается над активной карточкой (например: "ТЗ: Создайте сайт бухгалтерского учета для малого бизнеса")', verbose_name='Текст ТЗ'),
        ),
    ]
