# Generated by Django 5.2.8 on 2025-12-05 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_project_brief_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('landing', 'Лендинги'), ('ecommerce', 'Интернет-магазины'), ('corporate', 'Корпоративные сайты'), ('webapp', 'Веб-сервисы')], default='landing', max_length=50, verbose_name='Категория'),
        ),
    ]
