# Generated by Django 5.2.8 on 2025-12-05 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('subtitle', models.CharField(blank=True, help_text='Дополнительное описание (опционально)', max_length=255, verbose_name='Подзаголовок')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать')),
                ('is_featured', models.BooleanField(default=False, help_text='Карточка на всю ширину с темным фоном', verbose_name='Выделить')),
            ],
            options={
                'verbose_name': 'Тип сайта',
                'verbose_name_plural': 'Типы сайтов',
                'ordering': ['order'],
            },
        ),
    ]
