# Generated by Django 5.2.8 on 2025-12-05 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_websitetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitetype',
            name='detailed_description',
            field=models.TextField(blank=True, help_text='Для страницы типа сайта', verbose_name='Детальное описание'),
        ),
        migrations.AddField(
            model_name='websitetype',
            name='slug',
            field=models.SlugField(blank=True, help_text='Автоматически генерируется из названия', max_length=150, unique=True, verbose_name='URL (slug)'),
        ),
        migrations.AlterField(
            model_name='websitetype',
            name='description',
            field=models.TextField(help_text='Для карточки на главной', verbose_name='Краткое описание'),
        ),
        migrations.CreateModel(
            name='WebsiteTypeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=255, verbose_name='Название услуги')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('time_estimate', models.CharField(blank=True, help_text='Например: 5-7 дней', max_length=100, verbose_name='Срок выполнения')),
                ('price', models.CharField(help_text='Например: от 50 000 ₽', max_length=100, verbose_name='Стоимость')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('website_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_options', to='main.websitetype', verbose_name='Тип сайта')),
            ],
            options={
                'verbose_name': 'Опция расценок',
                'verbose_name_plural': 'Опции расценок',
                'ordering': ['website_type', 'order'],
            },
        ),
    ]
