# Generated by Django 5.2.8 on 2025-12-06 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_websitetype_detailed_description_websitetype_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='project_type',
            field=models.CharField(choices=[('mvp', 'MVP / стартап'), ('ecommerce', 'E-commerce / магазин'), ('corporate', 'Корпоративный сайт'), ('analysis', 'Анализ сайта'), ('from_scratch', 'Создание с нуля'), ('ads', 'Запуск рекламы'), ('support', 'Сопровождение/поддержка'), ('other', 'Другое')], default='mvp', max_length=50, verbose_name='Тип проекта'),
        ),
    ]
