# Generated by Django 5.2.8 on 2025-12-06 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_lead_project_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(blank=True, editable=False, upload_to='projects/thumbs/', verbose_name='Превью (авто)'),
        ),
    ]
