# Generated by Django 5.0 on 2025-12-09 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_project_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='budget',
            field=models.CharField(blank=True, max_length=100, verbose_name='Бюджет'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='message',
            field=models.TextField(blank=True, verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='project_type',
            field=models.CharField(blank=True, max_length=255, verbose_name='Тема / Тип сайта'),
        ),
    ]
