# Generated by Django 5.0 on 2025-12-13 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_lead_budget_alter_lead_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название проекта')),
                ('description', models.TextField(verbose_name='Описание')),
                ('document', models.FileField(blank=True, null=True, upload_to='orders/docs/', verbose_name='Документ')),
                ('image', models.ImageField(blank=True, null=True, upload_to='orders/images/', verbose_name='Фото')),
                ('status', models.CharField(choices=[('accepted', 'Принятые в работу'), ('in_progress', 'В работе'), ('testing', 'Тестирование'), ('completed', 'Завершенные')], default='accepted', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Активный заказ',
                'verbose_name_plural': 'Активные заказы',
                'ordering': ['-created_at'],
            },
        ),
    ]
