# Generated by Django 5.0 on 2025-12-13 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_activeorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activeorder',
            name='document',
        ),
        migrations.RemoveField(
            model_name='activeorder',
            name='image',
        ),
        migrations.CreateModel(
            name='ActiveOrderFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='orders/files/', verbose_name='Файл')),
                ('file_type', models.CharField(choices=[('image', 'Изображение'), ('document', 'Документ')], max_length=20, verbose_name='Тип')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='main.activeorder')),
            ],
            options={
                'verbose_name': 'Файл заказа',
                'verbose_name_plural': 'Файлы заказа',
            },
        ),
    ]
