# Generated by Django 5.0 on 2025-12-28 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_activeorder_document_remove_activeorder_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcase',
            name='seo_description',
            field=models.TextField(blank=True, help_text='Если пусто, используется сводка (summary)', verbose_name='SEO Description'),
        ),
        migrations.AddField(
            model_name='projectcase',
            name='seo_title',
            field=models.CharField(blank=True, help_text='Если пусто, используется название кейса', max_length=255, verbose_name='SEO Title'),
        ),
        migrations.AddField(
            model_name='websitetype',
            name='seo_description',
            field=models.TextField(blank=True, help_text='Если пусто, используется краткое описание', verbose_name='SEO Description'),
        ),
        migrations.AddField(
            model_name='websitetype',
            name='seo_title',
            field=models.CharField(blank=True, help_text='Если пусто, используется название типа', max_length=255, verbose_name='SEO Title'),
        ),
    ]
