# Generated by Django 5.0 on 2025-12-28 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_projectcase_seo_description_projectcase_seo_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='seo_description',
            field=models.TextField(blank=True, help_text='Если пусто, используется описание проекта', verbose_name='SEO Description'),
        ),
        migrations.AddField(
            model_name='project',
            name='seo_title',
            field=models.CharField(blank=True, help_text='Если пусто, используется название проекта', max_length=255, verbose_name='SEO Title'),
        ),
    ]
