# Generated by Django 5.2 on 2026-01-09 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_lead_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='experience',
            field=models.CharField(blank=True, help_text='Например: 6 лет', max_length=100, verbose_name='Опыт работы'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='specialization',
            field=models.TextField(blank=True, help_text='Навыки через запятую или точку с запятой', verbose_name='Специализация'),
        ),
    ]
