# Generated by Django 6.0.1 on 2026-01-14 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_teammember_experience_teammember_specialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='thumbnail_avif',
            field=models.ImageField(blank=True, editable=False, upload_to='projects/thumbs/', verbose_name='Превью AVIF (авто)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(blank=True, editable=False, upload_to='projects/thumbs/', verbose_name='Превью WebP (авто)'),
        ),
    ]
