# Generated by Django 5.2 on 2026-01-14 23:46

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_project_thumbnail_avif_alter_project_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='photo',
            field=models.ImageField(upload_to=main.models.team_photo_upload_to, verbose_name='Фото'),
        ),
    ]
