# Generated by Django 5.0 on 2026-01-17 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_fix_team_photo_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='projects/thumbs/', verbose_name='Превью WebP'),
        ),
        migrations.AlterField(
            model_name='project',
            name='thumbnail_avif',
            field=models.ImageField(blank=True, upload_to='projects/thumbs/', verbose_name='Превью AVIF'),
        ),
    ]
