# Generated by Django 6.0.2 on 2026-03-10 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_project_thumbnail_alter_project_thumbnail_avif'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activeorder',
            options={'ordering': ['-created_at'], 'verbose_name': 'Консультация', 'verbose_name_plural': 'Консультации'},
        ),
    ]
